//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.02 at 12:34:26 PM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://eazybytes.com/hrms", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.eazybytes.hrms;
